config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :categories
  resources :articles 
  get 'articles/category/:cat_id', :controller => 'articles', :action => 'showByCat'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    
    belongs_to :category, :optional => true
end

app/models/category.rb
class Category < ApplicationRecord
    
    has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'category'
    Category.new

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    @articles = Article.order('created_at DESC')
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to articles_url, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def showByCat
    @articles = Article.where("category_id = ?", params[:cat_id])
    render "artByCat"
  end
  
  def new
    @article = Article.new
  end

  def destroy
    @article.destroy
    flash[:success] = "Article deleted"
    redirect_to request.referrer || root_url
  end

  def edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :desc, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
 

  layout "application"

  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
    def my_button_to name, options = {}, html_options = {} # or some variation
        # eg. deal with options hash the way button_to deals with it here?
        content_tag :button, html_options = nil do
          raw name
        end
      end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def time_ago_in_words(from_time, options = {})
        distance_of_time_in_words(from_time, Time.now, options)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.erb
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
    </div>
  <% end %>
  <div class="container mx-auto">
    <a href="/categories" class=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded m-2" ><i class="fa fa-arrow-left"></i> Back</a>
  </div>                
  <div class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-sm md:mx-auto">
    <h1 class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center slide-in-bottom-h1">
    <% if controller.action_name == "edit" %>
    Edit
    <% else %>
    Add 
    <% end %> Article</h1>
    <div class="mb-4 md:flex md:flex-wrap md:justify-center fade-in">
      <%= form_for(article) do |f| %>
        <% if article.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

            <ul>
            <% article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="field-group mb-4 flex flex-col align-center justify-center ">
          <label class="field-label md:ml-2" for="#article_title">Name</label>
          <%= f.text_field :title %>
        </div>
        <div class="field-group mb-4 md:w-full flex flex-col align-center">
          <label class="field-label" for="#article_category">Category</label>
          <%= f.collection_select :category_id , Category.all, :id, :name, :prompt => 'Select One' %>
        </div>
        <div class="field-group mb-4 md:w-full flex flex-col align-center">
          <label class="field-label" for="#article_desc">Description</label>
          <%= f.text_area :desc %>
        </div>
        
        <%= f.submit :id => 'submit'%>
      <% end %>
    </div>
  </div>

app/views/articles/artByCat.html.erb
    
    <div class="container pt-24 md:pt-48 px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">
		
		<!--Left Col-->
		<div class="flex flex-col w-full xl:w-5/5 justify-center lg:items-start overflow-y-hidden p-4">
			<h1 class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center md:text-left slide-in-bottom-h1">Categorie <%= request.params[:cat_id] %> - Blog Ruby on Rails </h1>
			<p class="leading-normal text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle">Vous trouverez tous les articles de la categorie <%= request.params[:cat_id] %> !</p>
			
            <% @articles.each do |article| %>
                <div class="flex bg-white w-full justify-center md:justify-around items-center pb-24 mb-2 lg:pb-0 fade-in shadow">
                    <div class="flex-col w-full md:w-1/6 justify-end items-center fade-in p-2">
                        <img class="" src="https://img.icons8.com/cute-clipart/64/000000/user-male.png">
                        <p class="text-purple-300">Created :</br> <%= time_ago_in_words(article.created_at) %> ago</p>
                    </div>
                    <div class="flex w-full justify-center md:justify-around items-center">
                        
                        <p class="w-1/3"><%= article.title %></p>
                        <p class="text-gray-300 w-1/3"><%= article.desc.truncate(10) %></p>
                        <a href="<%= article_path(article.id) %>" class=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded m-2" ><i class="fa fa-eye"></i></a>
                    </div>
                </div>
            <% end %>
		</div>
		
		<!--Right Col-->
		<!-- <div class="w-full xl:w-2/5 py-6 overflow-y-hidden">
			<img class="w-5/6 mx-auto lg:mr-0 slide-in-bottom" src="assets/devices.svg">
		</div> -->
		
		<!--Footer-->
		<div class="w-full pt-16 pb-6 text-sm text-center md:text-left fade-in">
			<a class="text-gray-500 no-underline hover:no-underline" href="#">&copy; Blog 2019</a>
		</div>
		
	</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

<div class="text-center">
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

</div>

app/views/articles/index.html.erb
    
    <div class="container pt-24 md:pt-48 px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">
		
		<!--Left Col-->
		<div class="flex flex-col w-full xl:w-5/5 justify-center lg:items-start overflow-y-hidden p-4">
			<h1 class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center md:text-left slide-in-bottom-h1">Blog - Ruby on Rails</h1>
			<p class="leading-normal text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle">Vous trouverez tous les articles du blog Ruby !</p>
			<div class="flex justify-start">
			<a href="/articles/new" class=" fade-in bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded m-2" ><i class="fa fa-plus"></i> Add Article</a>
			</div>
            <% @articles.each do |article| %>
                <div class="flex bg-white w-full justify-center md:justify-around items-center py-6 px-4 mb-8 lg:pb-0 fade-in shadow">
                    <div class="flex-col w-full md:w-1/6 justify-end items-center fade-in p-2">
                        <img class="" src="https://img.icons8.com/cute-clipart/64/000000/user-male.png">
                        <p class="text-purple-300">Created :</br> <%= time_ago_in_words(article.created_at) %> ago</p>
                    </div>
                    <div class="flex w-full justify-center md:justify-between items-center">
                        <div class="flex-col">
							<p class="">TITRE : <%= article.title %></p>
							
								<p>CATEGORY : 
									<% @categories.each do |category| %>
										<% if article.category_id == category.id.to_s %>
											<a href="articles/category/<%= category.id %>"><span class="text-blue-500"><%= category.name %></span></a>
										<% end%>
									<% end %>
								</p>
								
							<p class="text-gray-500 ">DESCRIPTION : <%= article.desc.truncate(10) %></p>
						</div>
                        <div class="flex justify-around align-center w-1/4">
                        	<a href="/articles/<%= article.id %>" class=" bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded m-2" ><i class="fa fa-eye"></i></a>
                        	<a href="/articles/<%= article.id %>/edit" class=" bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded m-2" ><i class="fa fa-cog"></i></a>
                        	<%= button_to "X", article_path(article), method: :delete,class: "bg-blue-700 hover:bg-blue-800 text-white font-bold py-2 px-4 rounded m-2", data: { confirm: 'Are you sure?' }  %>
						</div>
					</div>
                </div>
            <% end %>
		</div>
		
		<!--Right Col-->
		<!-- <div class="w-full xl:w-2/5 py-6 overflow-y-hidden">
			<img class="w-5/6 mx-auto lg:mr-0 slide-in-bottom" src="assets/devices.svg">
		</div> -->
		
		<!--Footer-->
		<div class="w-full pt-16 pb-6 text-sm text-center md:text-left fade-in">
			<a class="text-gray-500 no-underline hover:no-underline" href="#">&copy; Blog 2019</a>
		</div>
		
	</div>

app/views/articles/new.html.erb
<%= render 'form', article: @article, category: @category %>

app/views/articles/show.html.erb
    
    <div class="container pt-24 md:pt-48 px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">
		
		<!--Left Col-->
		<div class="flex flex-col w-full xl:w-5/5 justify-center lg:items-start overflow-y-hidden p-4">
			<h1 class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center md:text-left slide-in-bottom-h1">Blog - Ruby on Rails</h1>
			<p class="leading-normal text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle">Article n° <%= @article.id %> - created <%= time_ago_in_words(@article.created_at) %> ago</p>
			
            <div class="bg-white flex w-full  pb-24 mb-2 lg:pb-0 fade-in shadow ">
                <div class="p-12 w-2/3">
                    <h2 class="text-purple-600 text-3xl font-weight-bold mt-4"><%= @article.title %></h2>
                    <h5 class="text-purple-500 font-weight-bold mt-4"><%= @article.category.name %></h5>
                    <p class="mt-4">Description : <br/>
                    <%= @article.desc %></p>
                </div>
                <div class="p-12 w-1/3 flex items-center justify-end">
                    <a href="#" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">
                        <i class="fa fa-cog"></i>
                    </a>
                    
                    <%= link_to "Delete", @article, method: :delete, data: { confirm: 'Are you sure?' }  %>
                    
                    
                    
                    
                </div>
            </div>
            
		</div>
		
		<!--Right Col-->
		<!-- <div class="w-full xl:w-2/5 py-6 overflow-y-hidden">
			<img class="w-5/6 mx-auto lg:mr-0 slide-in-bottom" src="assets/devices.svg">
		</div> -->
		
		<!--Footer-->
		<div class="w-full pt-16 pb-6 text-sm text-center md:text-left fade-in">
			<a class="text-gray-500 no-underline hover:no-underline" href="#">&copy; Blog 2019</a>
		</div>
		
	</div>

app/views/categories/_form.html.erb
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
    </div>
  <% end %>
  <div class="container mx-auto">
    <a href="/categories" class=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded m-2" ><i class="fa fa-arrow-left"></i> Back</a>
  </div>                
  <div class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-sm md:mx-auto">
    <h1 class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center md:text-left slide-in-bottom-h1">
    <% if controller.action_name == "edit" %>
    Edit
    <% else %>
    Add 
    <% end %> Category</h1>
    <div class="mb-4 md:flex md:flex-wrap md:justify-center">
      <%= form_for(category) do |f| %>
        <% if category.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

            <ul>
            <% category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="field-group mb-4 flex flex-col align-center ">
          <label class="field-label md:ml-2" for="#category_name">Name</label>
          <%= f.text_field :name %>
        </div>
        <div class="field-group mb-4 md:w-full flex flex-col align-center">
          <label class="field-label" for="#category_desc">Description</label>
          <%= f.text_area :desc %>
        </div>
        
        <%= f.submit :id => 'submit'%>
      <% end %>
    </div>
  </div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

<div class="text-center">
<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

</div>

app/views/categories/index.html.erb
    <div class="container pt-24 md:pt-48 px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">
		
		<!--Left Col-->
		<div class="flex flex-col w-full xl:w-2/5 justify-center lg:items-start overflow-y-hidden">
			<h1 class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center md:text-left slide-in-bottom-h1">Listes des categories du blog</h1>
			<p class="leading-normal text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle">Vous trouverez tous les posts par categorie directement !</p>
		
			<p class="text-blue-400 font-bold pb-8 lg:pb-6 text-center md:text-left fade-in">Categories :</p>
			<div class="flex justify-start">
			<a href="/categories/new" class=" fade-in bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded m-2" ><i class="fa fa-plus"></i> Add Category</a>
			</div>
			<div class="flex flex-wrap w-full justify-center md:justify-start pb-24 lg:pb-0 fade-in">
                <% @categories.each do |category| %>

				<div class="w-full flex align-center justify-between">
                    <a href="/articles/category/<%= category.id %>" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded m-2" ><%= category.name %></a>
					<div class="flex">
						<a class="bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded m-2" href="/categories/<%= category.id %>/edit"><i class="fa fa-cog"></i></a>
						<%= button_to 'destroy', category_path(category), method: :delete,class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded m-2", data: { confirm: 'Are you sure?' }  %>
					</div>
				</div>
						
				<% end %>
			</div>
			
			
		</div>
		
		<!--Right Col-->
		<div class="w-full xl:w-3/5 py-6 overflow-y-hidden">
			<img class="w-5/6 mx-auto lg:mr-0 slide-in-bottom" src="assets/devices.svg">
		</div>
		
		<!--Footer-->
		<div class="w-full pt-16 pb-6 text-sm text-center md:text-left fade-in">
			<a class="text-gray-500 no-underline hover:no-underline" href="#">&copy; Blog 2019</a>
		</div>
		
	</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudRuby</title>
    <%= csrf_meta_tags %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
  <div class="h-screen pb-14 bg-right bg-cover" style="background-image:url('<%= image_path('bg.svg') %>');">
    <div class="w-full container mx-auto p-6">
        
      <div class="w-full flex items-center justify-between">
        <a class="flex items-center text-indigo-400 no-underline hover:no-underline font-bold text-2xl lg:text-4xl"  href="/"> 
          <svg class="h-8 fill-current text-indigo-600 pr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 20a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm-5.6-4.29a9.95 9.95 0 0 1 11.2 0 8 8 0 1 0-11.2 0zm6.12-7.64l3.02-3.02 1.41 1.41-3.02 3.02a2 2 0 1 1-1.41-1.41z"/></svg> APP
        </a>
        
        <div class="flex w-1/2 justify-end content-center">		
          <a class="inline-block text-blue-300 no-underline hover:text-indigo-800 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4" data-tippy-content="@twitter_handle" href="/articles">
                      Articles
                  </a>
          <a class="inline-block text-blue-300 no-underline hover:text-indigo-800 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4 " data-tippy-content="#facebook_id" href="/categories">
                      Categories
                  </a>
        </div>
        
      </div>

    </div>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name , class: "bg-green-400 text-white py-2 px-2 text-center" %>
    <% end -%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
	<!--Main-->
	<div class="container pt-24 md:pt-48 px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">
		
		<!--Left Col-->
		<div class="flex flex-col w-full xl:w-2/5 justify-center lg:items-start overflow-y-hidden">
			<h1 class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center md:text-left slide-in-bottom-h1">Blog developped with Ruby on Rails</h1>
			<p class="leading-normal text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle">System with articles and categories - CRUD <br/>(create, read, update, delete) - Full responsive device</p>
		
			<p class="text-blue-400 font-bold pb-8 lg:pb-6 text-center md:text-left fade-in">Coming soon on : </p>
			<div class="flex w-full justify-center md:justify-start pb-24 lg:pb-0 fade-in">
				<img src="assets/App Store.svg" class="h-12 pr-4 bounce-top-icons">
				<img src="assets/Play Store.svg" class="h-12 bounce-top-icons">
			</div>

		</div>
		
		<!--Right Col-->
		<div class="w-full xl:w-3/5 py-6 overflow-y-hidden">
			<img class="w-5/6 mx-auto lg:mr-0 slide-in-bottom" src="assets/devices.svg">
		</div>
		
		<!--Footer-->
		<div class="w-full pt-16 pb-6 text-sm text-center md:text-left fade-in">
			<a class="text-gray-500 no-underline hover:no-underline" href="#">&copy; App 2019</a>
		</div>
		
	</div>